### ISSUE TITLE
Przestały działać linki sekcji w wydarzeniach

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-epf.org.pl#5]
Np. http://epf.org.pl/pl/wydarzenia/pdfplcee16/

![bug-epf](https://cloud.githubusercontent.com/assets/849975/9716985/233ac748-556f-11e5-8169-dd2dd741f0eb.PNG)

Przy okazji co tam robi domena purzycki.com ładująca skrypty?
![purzycki](https://cloud.githubusercontent.com/assets/849975/9717020/6fa1de6e-556f-11e5-905e-7fc4158d2d9e.PNG)

**Comment by KrzysztofMadejski** [comment]
@pkliks

**Comment by pkliks** [comment]
@KrzysztofMadejski czy macie screen/projekt jak powinno wyglądać. Dane dostępowe do wordpressa i ftp bym potrzebował?

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon , prośba o layout

@pkliks Jak zrobisz zmiany w github (pytanie, czy jest najnowsza wersja?) to wciągnę na serwer

**Comment by ArekSoldon** [comment]
to wyglądało tak, tj menu w linii białym fontem.

![main_0300](https://cloud.githubusercontent.com/assets/3994690/9829951/50ec4530-591c-11e5-9f2b-cb6fa7d5f8d5.jpg)

**Comment by pkliks** [comment]
@KrzysztofMadejski A jakiś zrzut bazy żeby testową postawił u siebie?
Odnośnie pytania czy jest najnowsze? Możesz to sprawdzić? Ja nie mam możliwości, a głupio by było gdybym działał na starej wersji.
